
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import TanStackQueryProvider from "@/components/TanStackQueryProvider";
import { Toaster } from "@/components/ui/sonner";
import Header  from "@/components/Navbar";
import SessionProviderWrapper from "@/components/SessionProviderWrapper/SessionProviderWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
        <head />
        <body>
      <SessionProviderWrapper>
          <TanStackQueryProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
             <div className="relative w-full flex items-center justify-center ">
          <Header />
        </div>
            
            {children}
            <Toaster/>
          </ThemeProvider>
          </TanStackQueryProvider>
         </SessionProviderWrapper>
        </body>
      </html>
  );
}
